name: where_are_you
description: Where are you?
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^4.0.3
  file: ^6.1.2
  flutter:
    sdk: flutter
  geocoder_offline: ^0.2.1
  meta: ^1.7.0
  nm: ^0.4.1
  provider: ^6.0.1
  xml: ^5.3.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
