name: flutter_time_zone_map
description: Time zone map.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 
  file: 
  flutter_map: 
  flutter_typeahead: 
  freezed_annotation: 
  geocoder_offline:
  latlong2: 
  provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: 
  freezed: 
  json_serializable: 

flutter:
  uses-material-design: true
  assets:
    - assets/
